#%RAML 1.0 DataType

type:
  properties:
    firstName:
      type: string
      required: true
      example: John
    lastName:
      type: string
      required: true
      example: Doe
    address:
      type: string
      required: true
      example: 1 st street 
    orderId:
      type: string
      required: true
      example: a003k00000TudZ7AAJ