#%RAML 1.0 DataType

properties:
    id:
      type: string
      required: true
    category:
      type: string
      required: true
      example: Hoodie
    quantity:
      type: number
      required: true
    size:
      type: string
      required: true
      example: S
    orderId:
      type: string
      required: true
      example: a003k00000TudZ7AAJ