#%RAML 1.0 NamedExample
order-get-example:
  {"order":
             [{
          "poNumber": "123461",
  "signatureRequiredFlag": false,
  "shipInstructions": "Don't break it",
  "giftWrapFlag": true,
  "giftWrapMessage": "You rock!",
  "currencyCode": "USD",
  "subTotal": 41.5,
  "email": "test@test.com"
}]
}